[build]
  base = "frontend"
  command = "npm run build"
<<<<<<< HEAD
  publish = "dist"
=======
  publish = "frontend/dist"
>>>>>>> origin/SimpleLogz/Test

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200